### ISSUE TITLE
Bitsetter not re zeroing work off set

### ISSUE THREAD

**Issue by nickrooney** [neilferreri/CNCjs-Macros#2]
Im having a little bit of an issue with the bit setter macros. Whenever I do A tool change mid job, or changing it in general, its like it doesnt reset the work offset Z height. I ran into an issue on a job, so then i did a test. I took an endmill, stuck it out as much as I could, ran the initial macro, and zerod it off the workpiece. Then I shortened it up, and tried both the Initial and in game macro, got the endmill to touch the workpiece, and the work coordinates says that I have 16mm let to go to get to zero. Any ideas?

**Comment by neilferreri** [comment]
Set your work zero before you run the initial tool macro.
[Procedure](https://github.com/cncjs/CNCjs-Macros/blob/192a9f4eecb6e5990b99c07a2da29b477567897a/Initial%20%26%20New%20Tool/Procedure#L2-L5)

**Comment by neilferreri** [comment]
@nickrooney Did you get this sorted out?

**Comment by nickrooney** [comment]
Just tried it out and thats seems to be the issue. Nothing like some good ol user error lol. Thanks for your help I appreciate it and your patients for my apparent inability to read lol

**Comment by neilferreri** [comment]
No problem. 
Any time you reset your work zero, you'll need to run the initial tool macro again. You can run it right after you set zeros or right before you change tools.
