### ISSUE TITLE
Prompt for tool diameter when probing for zero?

### ISSUE THREAD

**Issue by TJ-Houghton** [neilferreri/CNCjs-Macros#3]
Is it possible to add a prompt in the macro for entering the tool diameter when zeroing?  It would be nice not to have to edit the macro each time I am zeroing, or install a 1/4" end mill if I am not planning on starting out with that.

Also, I noticed that in the C3D_3axis_probe file, the tool diameter entered in the macro is actually the radius, which is causing a zero point shift of half the diameter of the tool.

**Comment by neilferreri** [comment]
Input prompts would be great, but that's not within the scope of macros as they're currently set up.

As far as the endmill diameter issue your having, what size endmill are you using, how do you have it entered in the macro and what are you noticing?

**Comment by TJ-Houghton** [comment]
Well that's too bad about the input.

I have my macro set up for a 1/4" end mill but sometimes I use an 1/8" end mill.  I fixed the macro issue on my copy of cncjs so I don't have any issues, but I didn't notice it until after I ran a job and noticed that my zero was off by 1/8" in both x and y directions.  The macro specifies a diameter and sets the value to 3.175mm (which is the radius of a 1/4" end mill), and then later on when it calculates the offset after touching the probe, it divides that number by 2, instead of using it directly.  Minor issue and long as the user has enough stock on the table, usually isn't an issue, but I wanted to let you know of the typo in the macro you have posted.

Thanks,
TJ

**Comment by neilferreri** [comment]
You're supposed to enter the diameter of your endmill where it says.  The diameter of your 1/4" endmill is 6.35mm.  The 3.175mm in the example is assuming a 1/8" diameter endmill.  I later divide that by two, intentionally, to use the radius to offset.  Most people think of endmill size by diameter.
I hope that makes sense.  Basically, just enter your endmill DIAMETER where it says `%ENDMILL_DIAMETER`.
Closing this issue, but feel free to comment more.

**Comment by TJ-Houghton** [comment]
I use a 1/4” end mill so often that I assume it’s the default for everyone else😂

**Comment by neilferreri** [comment]
😃 
I don't really know why I used an 1/8" by default.  I try to cut everything with 1/4" too.
